### ISSUE TITLE
Screenshots for each app type

### ISSUE THREAD

**Issue by DJRM2021** [MicrosoftDocs/windows-dev-docs#3628]
It may be a lot better for novice developers to learn if we provided a screenshot of a sample per app type. So example, win32 window with controls, wpf window with controls, WinForms window with few controls, UWP app with controls, etc.

If I was a beginner, I would really appreciate it if I can see how each app from different "app types" look like.
Please provide the screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25fcf332-0c1b-7c10-406d-bfd5f6eef952
* Version Independent ID: d2b12b06-f936-204b-1be7-9ca844ceff43
* Content: [Overview of app development options - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/?tabs=cpp-win32)
* Content Source: [hub/apps/get-started/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
While I understand the sentiment, there's not really one single "look" for each sort of app - that's a question of which controls you choose to implement and how you structure the UI of your app as a whole. In this page, we've chosen to prioritize the technical specifics rather than a look at a given sample UI, which is mostly a factor of a user's implementation rather than the app type itself.
